package com.ashutosh.employeetesting.model;

public enum Department {

	FINANCE,
    HUMAN_RESOURCES,
    MARKETING,
    RESEARCH_AND_DEVELOPMENT,
    IT,
    CUSTOMER_SERVICE,
    OPERATIONS_MANAGEMENT,
    ADMINISTRATION,
    PURCHASING,
    PRODUCTION,
    SALES,
    SALES_DEPARTMENT,
    ACCOUNTING,
    MAINTENANCE_DEPARTMENT,
    DESIGN,
    QUALITY_MANAGEMENT,
    BUSINESS_DEVELOPMENT,
    LAW,
    PRODUCT_DEVELOPMENT,
    HUMAN_RESOURCE_DEVELOPMENT,
    DISTRIBUTION,
    DISPATCH_DEPARTMENT,
    STORE_DEPARTMENT,
    MANAGEMENT
}
